// Regenerate after adding/changing a portfolio photo. Requires Node + sharp.
// Usage: node tool/generate_image_previews.cjs
// These tiny, embedded previews do not trigger additional image HTTP requests.
const fs = require('node:fs/promises');
const path = require('node:path');
const sharp = require('sharp');

const root = path.resolve(__dirname, '..');
async function dartSources(directory) {
  const entries = await fs.readdir(directory, {withFileTypes: true});
  return (await Promise.all(entries.map(async entry => {
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) return dartSources(file);
    return file.endsWith('.dart') && !file.endsWith('asset_image_previews.dart')
      ? [await fs.readFile(file, 'utf8')] : [];
  }))).flat();
}

async function main() {
  const sources = (await dartSources(path.join(root, 'lib'))).join('\n');
  const assets = [...new Set(sources.match(/assets\/images\/[\w/.-]+\.(?:png|jpe?g|webp)/g))].sort();
  const previews = {};
  let totalBytes = 0;
  for (const asset of assets) {
    const bytes = await sharp(path.join(root, asset)).rotate()
      .resize({width: 80, height: 80, fit: 'inside', withoutEnlargement: true})
      .webp({quality: 48, effort: 6}).toBuffer();
    previews[asset] = bytes.toString('base64');
    totalBytes += bytes.length;
  }
  const dart = `// GENERATED by tool/generate_image_previews.cjs. Do not edit by hand.
import 'dart:convert';
import 'dart:typed_data';

final _decodedPreviews = <String, Uint8List>{};

/// Tiny versions of the real photos, available without a network round trip.
Uint8List? assetPreviewBytes(String asset) {
  final encoded = assetImagePreviews[asset];
  if (encoded == null) return null;
  return _decodedPreviews.putIfAbsent(asset, () => base64Decode(encoded));
}

const assetImagePreviews = <String, String>{
${Object.entries(previews).map(([asset, bytes]) => `  '${asset}': '${bytes}',`).join('\n')}
};
`;
  await fs.writeFile(path.join(root, 'lib/data/asset_image_previews.dart'), dart);
  console.log(`Generated ${assets.length} real-image previews (${totalBytes} bytes before base64).`);
}
main().catch(error => {console.error(error); process.exitCode = 1;});
